[package]
name = "ya-vpn"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-core-model = { version = "^0.3", features = ["activity", "market"] }
ya-client-model = { version = "0.3", features = ["sgx"] }
ya-net = "0.2"
ya-persistence = "0.2"
ya-service-api = "0.1"
ya-service-api-interfaces = "0.1"
ya-service-api-web = "0.1"
ya-service-bus = "0.4"
ya-utils-networking = { version = "0.1", default-features = false, features = ["vpn"]}

actix = "0.10"
actix-web = "3.2"
actix-web-actors = "3"
anyhow = "1.0"
bytes = "0.5"
env_logger = "0.7"
futures = "0.3"
hex = "0.4"
ipnet = "2.3"
managed = "0.7.2"
log = "0.4"
mime = "0.3.16"
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smoltcp = { version = "0.7.0" }
thiserror = "1.0"
tokio = { version = "0.2.11", features = ["time"] }

[dev-dependencies]
ya-sb-router = "0.4"
